Project_Dataview/CLO_Project/CLO_Project/CLO_Project/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/uwsgi/',include('django_uwsgi.urls')),
    path('admin/', admin.site.urls),
]

Project_Dataview/CLO_Project/CLO_Project/Fetch_data/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('',views.batchInfo,name='batchInfo'),
]

Project_Dataview/CLO_Project/CLO_Project/users/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(
        regex=r'^exceptions$',
        view=views.BatchExceptionDatatableView.as_view(),
        name='exceptions'
    ),
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),

]

Project_Dataview/CLO_Project/config/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

admin.site.site_header = settings.ADMIN_SITE_HEADER
urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='pages/home.html'), name='home'),
    url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'), name='about'),

    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, admin.site.urls),

    # User management
    url(r'^users/', include('clo_project.users.urls', namespace='users')),
    url(r'^accounts/', include('allauth.urls')),

    # Your stuff: custom urls includes go here


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar
        urlpatterns = [
            url(r'^__debug__/', include(debug_toolbar.urls)),
        ] + urlpatterns

Project_Dataview/CLO_Project/CLO_Project/Fetch_data/models.py
from django.db import models

# Create your models here.

Project_Dataview/CLO_Project/CLO_Project/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _


@python_2_unicode_compatible
class User(AbstractUser):

    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = models.CharField(_('Name of User'), blank=True, max_length=255)

    def __str__(self):
        return self.username

    def get_absolute_url(self):
        return reverse('users:detail', kwargs={'username': self.username})

#@python_2_unicode_compatible
class Blog(models.Model):
    name = models.CharField(max_length=100)
    tagline = models.TextField()

    def __str__(self):
        return self.name


#@python_2_unicode_compatible
class Author(models.Model):
    name = models.CharField(max_length=50)
    email = models.EmailField()

    def __str__(self):
        return self.name

class BatchException(models.Model):

    class Meta:
        db_table = "batchException"
#        db_tablespace = "web"

    batchExceptionID = models.IntegerField(primary_key=True)
    batchID = models.IntegerField()
    createdBy = models.CharField(max_length=500)
    createdOn= models.DateField()
    modifiedBy = models.CharField(max_length=500)
    modifiedOn= models.DateField()
    fileName = models.CharField(max_length=500)
    exceptionReason = models.CharField(max_length=5000)

    def __str__(self):
        return self.fileName

Project_Dataview/CLO_Project/CLO_Project/users/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _


@python_2_unicode_compatible
class User(AbstractUser):

    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = models.CharField(_('Name of User'), blank=True, max_length=255)

    def __str__(self):
        return self.username

    def get_absolute_url(self):
        return reverse('users:detail', kwargs={'username': self.username})

#@python_2_unicode_compatible
class Blog(models.Model):
    name = models.CharField(max_length=100)
    tagline = models.TextField()

    def __str__(self):
        return self.name


#@python_2_unicode_compatible
class Author(models.Model):
    name = models.CharField(max_length=50)
    email = models.EmailField()

    def __str__(self):
        return self.name

class BatchException(models.Model):
    batchExceptionID = models.IntegerField()
    batchID = models.IntegerField()
    createdBy = models.CharField(max_length=500)
    createdOn= models.DateField()
    modifiedBy = models.CharField(max_length=500)
    modifiedOn= models.DateField()
    fileName = models.CharField(max_length=500)
    exceptionReason = models.CharField(max_length=5000)

    def __str__(self):
        return self.fileName

Project_Dataview/CLO_Project/CLO_Project/Fetch_data/views.py
from django.shortcuts import render
from django.http import HttpResponse, JsonResponse
from django.db import connection
import pyodbc




# Create your views here.
def batchInfo(request):
    connection = pypyodbc.connect('Driver={SQL Server};' 'server=sql-clo-prod.c0cqs7rsnqyl.us-east-1.rds.amazonaws.com;' 'Database= clo_factorydb;' 'uid=clowebuser; pwd=R8b}EtjgP$n_H')
    cursor=connection.cursor()
    #return HttpResponse('Hello world')
    cursor.execute("SELECT batchID FROM rawload.batchException;")
    rows = cursor.fetchall()
    data = []
    for row in rows:
        data.append(row.batchID)
    return render(request, "sampledata.html", {"batch_info": data})

Project_Dataview/CLO_Project/CLO_Project/users/users/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView
from datatableview.views import XEditableDatatableView
from datatableview import helpers

from .models import User,  BatchException

class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})


class UserUpdateView(LoginRequiredMixin, UpdateView):

    fields = ['name', ]

    # we already imported User in the view code above, remember?
    model = User

    # send the user back to their own page after a successful update
    def get_success_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})

    def get_object(self):
        # Only get the User record for the user making the request
        return User.objects.get(username=self.request.user.username)

class BatchExceptionListView(ListView):
     model = BatchException
     fields = ['batchExceptionId', 'fileName', 'exceptionReason', 'ModifiedBy']
     #slug_field = 'batchExceptionId'
     #slug_url_kwarg = 'batchExceptionId'
    
     
class UserListView(LoginRequiredMixin, ListView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'

"""
class XEditableColumnsDatatableView(XEditableDatatableView):
    model = Entry
    datatable_options = {
 	'columns': [
                'id',
                ("Headline", 'headline', helpers.make_xeditable),
                ("Blog", 'blog', helpers.make_xeditable),
                ("Published date", 'pub_date', helpers.make_xeditable),
        ]
    }
"""

Project_Dataview/CLO_Project/CLO_Project/users/views.py
from datatableview import helpers
from datatableview.views import DatatableView, XEditableDatatableView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView

from .models import BatchException, User


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})


class UserUpdateView(LoginRequiredMixin, UpdateView):

    fields = ['name', ]

    # we already imported User in the view code above, remember?
    model = User

    # send the user back to their own page after a successful update
    def get_success_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})

    def get_object(self):
        # Only get the User record for the user making the request
        return User.objects.get(username=self.request.user.username)

class UserListView(LoginRequiredMixin, ListView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'


class BatchExceptionDatatableView(XEditableDatatableView):
    model = BatchException
    #template_name = 'users/x_editable_columns.html'
    datatable_options = {
 	'columns': [
                ('ID', 'batchExcpetionID', helpers.make_xeditable),
                ('Batch Id', 'batchID', helpers.make_xeditable),
                ('Created By', 'createdBy', helpers.make_xeditable),
                ('Created Date', 'createdOn', helpers.make_xeditable),
                ('Modified By', 'modifiedBy', helpers.make_xeditable),
                ('Modified Date', 'modifiedOn', helpers.make_xeditable),
                ('File Name', 'fileName', helpers.make_xeditable) 
        ]
    }

    implementation = u"""
    class BatchExceptionDatatableView(XEditableDatatableView):
        model = BatchException
        template_name = 'users/x_editable_columns.html'
        datatable_options = {
 	    'columns': [
                ('ID', 'batchExcpetionID', helpers.make_xeditable),
                ('Batch Id', 'batchID', helpers.make_xeditable),
                ('Created By', 'createdBy', helpers.make_xeditable),
                ('Created Date', 'createdOn', helpers.make_xeditable),
                ('Modified By', 'modifiedBy', helpers.make_xeditable),
                ('Modified Date', 'modifiedOn', helpers.make_xeditable),
                ('File Name', 'fileName', helpers.make_xeditable)
            ]
        }                                                                                                                                    
    </pre>                                                                                                                                         <pre class="brush: javascript">                                                                                                                // Page javascript                                                                                                                             datatableview.auto_initialize = false;                                                                                                         $(function(){                                                                                                                                      var xeditable_options = {};
             datatableview.initialize($('.datatable'), {                                                                                                   fnRowCallback: datatableview.make_xeditable(xeditable_options),                                                          
        });                                                                                                                           
    })"""

Project_Dataview/CLO_Project/CLO_Project/templates/403_csrf.html
{% extends "base.html" %}

{% block title %}Forbidden (403){% endblock %}

{% block content %}
<h1>Forbidden (403)</h1>

<p>CSRF verification failed. Request aborted.</p>
{% endblock content %}

Project_Dataview/CLO_Project/CLO_Project/templates/base.html
{% load static i18n %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}Trepp{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
    <![endif]-->

{% block css %}
    <script src="http://code.jquery.com/jquery-2.0.3.min.js"></script>
    <script type="text/javascript" charset="utf8" src="http://cdn.datatables.net/1.10.0/js/jquery.dataTables.min.js"></script>
    <link rel="stylesheet" type="text/css" href="http://cdn.datatables.net/1.10.0/css/jquery.dataTables.css">
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet" />
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
    <script type="text/javascript" charset="utf8" src="/static/js/datatableview.js"></script>
    <link href="http://alexgorbatchev.com/pub/sh/current/styles/shCore.css" rel="stylesheet" type="text/css" />
    <link href="http://alexgorbatchev.com/pub/sh/current/styles/shThemeDefault.css" rel="stylesheet" type="text/css" />
    <script src="http://alexgorbatchev.com/pub/sh/current/scripts/shCore.js" type="text/javascript"></script>
    <script src="http://alexgorbatchev.com/pub/sh/current/scripts/shAutoloader.js" type="text/javascript"></script>
    <script src="http://alexgorbatchev.com/pub/sh/current/scripts/shBrushPython.js" type="text/javascript"></script>

    <style type="text/css">
      .nav.sidebar a {
      border-right: 1px solid white;
      padding: 5px 10px;
      }
      .nav.sidebar a.active {
      font-weight: bold;
      background-color: #f0f0f0;
      border-color: #428bca;
      }
      .nav.sidebar li.divider {
      margin: 0.5em;
      border-top: 1px solid #dfdfdf;
      }
    </style>
    <script type="text/javascript">
      $(function(){
      SyntaxHighlighter.all();
      var path = window.location.pathname;
      $('.nav.sidebar > li > a[href="'+path+'"]').addClass("active");
    });
</script>

<script src="http://alexgorbatchev.com/pub/sh/current/scripts/shBrushJScript.js" type="text/javascript"></script>
<link href="{{ STATIC_URL }}datepicker/css/datepicker.css" rel="stylesheet"/>
<script src="{{ STATIC_URL }}datepicker/js/bootstrap-datepicker.js"></script>
<link href="//cdnjs.cloudflare.com/ajax/libs/x-editable/1.5.0/bootstrap3-editable/css/bootstrap-editable.css" rel="stylesheet"/>
<script src="//cdnjs.cloudflare.com/ajax/libs/x-editable/1.5.0/bootstrap3-editable/js/bootstrap-editable.min.js"></script>
{% endblock %}

  </head>

  <body>

    <div class="m-b-1">
      <nav class="navbar navbar-expand-md navbar-light bg-light">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href="{% url 'home' %}">Trepp</a>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
	    
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'users:exceptions' %}">Exceptions<span class="sr-only">(current)</span></a>
            </li>
	    <!--
            <li class="nav-item">
              <a class="nav-link" href="{% url 'about' %}">About</a>
            </li> -->
            {% if request.user.is_authenticated %}
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a class="nav-link" href="{% url 'users:detail' request.user.username  %}">{% trans "My Profile" %}</a>
              </li>
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a class="nav-link" href="{% url 'account_logout' %}">{% trans "Sign Out" %}</a>
              </li>
            {% else %}
              <!--<li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a id="sign-up-link" class="nav-link" href="{% url 'account_signup' %}">{% trans "Sign Up" %}</a>
              </li>-->
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a id="log-in-link" class="nav-link" href="{% url 'account_login' %}">{% trans "Sign In" %}</a>
              </li>
            {% endif %}
          </ul>
        </div>
      </nav>

    </div>

    <div class="container">

      {% if messages %}
          {% for message in messages %}
              <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message }}</div>
          {% endfor %}
      {% endif %}

      {% block content %}
	      <!-- content goes here -->
      {% endblock content %}

    </div> <!-- /container -->

    {% block modal %}{% endblock modal %}

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    {% block javascript %}     
      

    {% endblock javascript %}
  </body>
</html>
 

Project_Dataview/CLO_Project/CLO_Project/templates/sampledata.html
{% for each in batch_info %}
	{{each}}
{% endfor %}